version: "3.9"

services:
  db:
    image: postgres
    volumes: 
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dailymenu
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  django: &django
    build: 
      context: .
      dockerfile: compose/django/dev.Dockerfile
    container_name: django
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes: 
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=dailymenu
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
